(ns github.copilot-sdk.api-surface
  "API-surface drift guard support.

   Computes a deterministic snapshot of the supported public contract:

   - explicitly enrolled public namespaces
   - curated public vars in those namespaces, including kind, canonical
     arglists, and compatibility-relevant metadata
   - normalized registered fdef forms attached to those vars
   - registered spec-key membership in the curated idiom specs namespace

   The snapshot is checked in at `resources/github/copilot_sdk/api_surface.edn`.
   Regenerate it after an intentional contract change with:

       bb api-surface:update"
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.set :as set]
            [clojure.spec.alpha :as s]
            [clojure.spec.test.alpha :as stest]
            [clojure.string :as str]
            [github.copilot-sdk]
            [github.copilot-sdk.client]
            [github.copilot-sdk.factory]
            [github.copilot-sdk.helpers]
            [github.copilot-sdk.logging]
            [github.copilot-sdk.session]
            [github.copilot-sdk.specs]
            [github.copilot-sdk.tool-set]
            [github.copilot-sdk.tools]))

(def ^:private format-version 2)

(def ^:private public-namespaces
  (sorted-set
   'github.copilot-sdk
   'github.copilot-sdk.client
   'github.copilot-sdk.factory
   'github.copilot-sdk.helpers
   'github.copilot-sdk.instrument
   'github.copilot-sdk.logging
   'github.copilot-sdk.session
   'github.copilot-sdk.specs
   'github.copilot-sdk.tool-set
   'github.copilot-sdk.tools))

(def ^:private idiom-spec-ns 'github.copilot-sdk.specs)

(def ^:private named-var-exclusions
  {'github.copilot-sdk.factory
   {'->FactoryHandle
    "Compiler-generated positional constructor for the private FactoryHandle record."
    'map->FactoryHandle
    "Compiler-generated map constructor for the private FactoryHandle record."}
   'github.copilot-sdk.session
   {'->CopilotSession
    "Compiler-generated positional constructor; sessions are created by the client API."
    'map->CopilotSession
    "Compiler-generated map constructor; sessions are created by the client API."}})

(def ^:private proxy-intern-exclusion
  {:namespace 'github.copilot-sdk.client
   :pattern
   #"^github\.copilot_sdk\.client\.proxy\$(java\.io\.Filter(?:Input|Output)Stream)\$[0-9a-f]+$"
   :expected-targets
   #{"java.io.FilterInputStream" "java.io.FilterOutputStream"}
   :reason
   "Classes generated by the two private non-closing stdio proxy helpers."})

(def ^:private named-spec-exclusions
  "Idiom spec registry keys deliberately kept out of the public API snapshot.
   Each entry names one experimental spec key and states why it is excluded.
   The key must still be registered in the idiom spec namespace; a removed key
   makes its entry stale and fails snapshot generation, forcing a reviewer to
   delete the entry. Membership is a narrow, reasoned allowlist, never a
   pattern."
  {:github.copilot-sdk.specs/permission-response-capability
   "Experimental assisted-approval decision-context capability, part of the same experimental permission-decision-context / attributed-permission-result surface. Not stable public API."})

(defn- validate-named-spec-exclusions!
  "Fail closed on stale or unreasoned idiom spec exclusions. `present` is the
   set of idiom spec keys currently registered. Every excluded key must carry a
   non-blank reason and still be registered."
  [present exclusions]
  (doseq [[spec-key reason] exclusions]
    (when (str/blank? reason)
      (throw (ex-info "Spec key exclusion requires a reason"
                      {:spec-key spec-key})))
    (when-not (contains? present spec-key)
      (throw (ex-info "Stale spec key exclusion"
                      {:spec-key spec-key :reason reason}))))
  exclusions)

(def snapshot-resource
  "Classpath resource path of the checked-in snapshot."
  "github/copilot_sdk/api_surface.edn")

(defn- snapshot-source-file []
  (io/file "resources" snapshot-resource))

(defn- stable-compare [left right]
  (compare (pr-str left) (pr-str right)))

(defn- normalize-symbol [sym]
  (let [normalized-name
        (-> (name sym)
            (str/replace #"__\d+__auto__$" "__auto__")
            (str/replace #"__\d+#$" "__gensym"))]
    (if-let [sym-ns (namespace sym)]
      (symbol sym-ns normalized-name)
      (symbol normalized-name))))

(defn- normalize-form [form]
  (let [form (if (instance? clojure.lang.IObj form)
               (with-meta form nil)
               form)]
    (cond
      (class? form)
      (symbol (.getName ^Class form))

      (symbol? form)
      (normalize-symbol form)

      (map? form)
      (into (sorted-map-by stable-compare)
            (map (fn [[key value]]
                   [(normalize-form key) (normalize-form value)]))
            form)

      (set? form)
      (into (sorted-set-by stable-compare)
            (map normalize-form)
            form)

      (vector? form)
      (mapv normalize-form form)

      (list? form)
      (apply list (map normalize-form form))

      (seq? form)
      (doall (map normalize-form form))

      :else
      form)))

(defn- assert-stable-edn! [context value]
  (let [printed (pr-str value)]
    (when (re-find #"__\d+(?:__auto__|#)" printed)
      (throw (ex-info "Raw auto-gensym counter in API snapshot value"
                      {:context context :value value})))
    (when (re-find #"(?:^|[.$])proxy\$" printed)
      (throw (ex-info "Generated proxy identifier in API snapshot value"
                      {:context context :value value})))
    (when (str/includes? printed "#object[")
      (throw (ex-info "Non-EDN object in API snapshot value"
                      {:context context :value value})))
    (let [round-tripped
          (try
            (edn/read-string printed)
            (catch RuntimeException error
              (throw (ex-info "API snapshot value is not readable EDN"
                              {:context context
                               :printed printed}
                              error))))]
      (when-not (= value round-tripped)
        (throw (ex-info "API snapshot value is not stable EDN"
                        {:context context
                         :value value
                         :round-tripped round-tripped})))))
  value)

(defn- var-kind [v]
  (let [m (meta v)]
    (cond
      (:macro m) :macro
      (fn? @v) :fn
      :else :value)))

(defn- var-entry [v]
  (let [m (meta v)]
    (cond-> {:kind (var-kind v)}
      (:arglists m) (assoc :arglists (normalize-form (:arglists m)))
      (:dynamic m) (assoc :dynamic true)
      (:deprecated m) (assoc :deprecated true)
      (:experimental m) (assoc :experimental true))))

(defn- validate-named-exclusions!
  [namespace publics exclusions]
  (doseq [[sym reason] exclusions]
    (when (str/blank? reason)
      (throw (ex-info "Public var exclusion requires a reason"
                      {:namespace namespace :var sym})))
    (let [v (get publics sym)]
      (when-not v
        (throw (ex-info "Stale public var exclusion"
                        {:namespace namespace :var sym :reason reason})))
      (when (:no-doc (meta v))
        (throw (ex-info "Public var exclusion is redundant with ^:no-doc"
                        {:namespace namespace :var sym :reason reason})))))
  exclusions)

(defn- proxy-target [sym]
  (some-> (re-matches (:pattern proxy-intern-exclusion) (name sym))
          second))

(defn- proxy-interns [publics]
  (into {}
        (keep (fn [[sym v]]
                (when-let [target (proxy-target sym)]
                  [sym {:target target :var v}])))
        publics))

(defn- validate-proxy-exclusion! [namespace publics]
  (if (= namespace (:namespace proxy-intern-exclusion))
    (let [matches (proxy-interns publics)
          targets (set (map (comp :target val) matches))]
      (when-not (and (= targets (:expected-targets proxy-intern-exclusion))
                     (= (count matches) (count targets)))
        (throw (ex-info "Stale or unexpected generated proxy intern exclusion"
                        {:namespace namespace
                         :reason (:reason proxy-intern-exclusion)
                         :expected-targets
                         (:expected-targets proxy-intern-exclusion)
                         :actual-targets targets
                         :actual-vars (set (keys matches))})))
      (set (keys matches)))
    #{}))

(defn- generated-record-factory? [sym]
  (or (str/starts-with? (name sym) "map->")
      (boolean (re-matches #"^->[A-Z].+" (name sym)))))

(defn- generated-proxy-intern? [sym]
  (str/includes? (name sym) ".proxy$"))

(defn- assert-no-generated-interns! [namespace vars]
  (let [unexpected
        (->> (keys vars)
             (filter #(or (generated-record-factory? %)
                          (generated-proxy-intern? %)))
             sort
             vec)]
    (when (seq unexpected)
      (throw (ex-info
              "Unexpected compiler-generated intern in supported API namespace"
              {:namespace namespace :vars unexpected}))))
  vars)

(defn public-vars
  "Map of `symbol -> contract metadata` for a supported public namespace.

   Vars marked `^:no-doc`, named compiler artifacts with reviewed exclusions,
   and the two validated client stdio proxy class interns are excluded."
  [namespace]
  (let [publics (ns-publics namespace)
        named-exclusions (get named-var-exclusions namespace {})
        _ (validate-named-exclusions! namespace publics named-exclusions)
        proxy-exclusions (validate-proxy-exclusion! namespace publics)
        excluded (into (set (keys named-exclusions)) proxy-exclusions)
        vars (into (sorted-map)
                   (comp
                    (remove (fn [[sym v]]
                              (or (:no-doc (meta v))
                                  (contains? excluded sym))))
                    (map (fn [[sym v]]
                           [sym (var-entry v)])))
                   publics)]
    (assert-no-generated-interns! namespace vars)))

(defn- qualified-symbol [namespace sym]
  (symbol (str namespace) (str sym)))

(defn- fdef-entries [namespace vars]
  (into (sorted-map)
        (keep
         (fn [sym]
           (let [qualified (qualified-symbol namespace sym)]
             (when-let [spec (s/get-spec qualified)]
               (let [form (normalize-form (s/form spec))]
                 [qualified (assert-stable-edn!
                             {:namespace namespace :fdef qualified}
                             form)])))))
        (keys vars)))

(defn spec-keys []
  (let [registered (->> (s/registry)
                        keys
                        (filter keyword?)
                        (filter #(= (namespace %) (str idiom-spec-ns)))
                        set)
        _ (validate-named-spec-exclusions! registered named-spec-exclusions)
        excluded (set (keys named-spec-exclusions))]
    (->> registered
         (remove excluded)
         sort
         vec)))

(defn- stest-instrumented-vars-atom []
  (var-get (ns-resolve 'clojure.spec.test.alpha 'instrumented-vars)))

(defn- instrumentation-state []
  (let [registry (stest-instrumented-vars-atom)
        entries @registry]
    {:entries entries
     :roots (into {}
                  (map (fn [v] [v @v]))
                  (keys entries))}))

(defn- same-instrumentation-state? [left right]
  (and (= (:entries left) (:entries right))
       (= (set (keys (:roots left)))
          (set (keys (:roots right))))
       (every? (fn [[v root]]
                 (identical? root (get-in right [:roots v])))
               (:roots left))))

(defn- restore-instrumentation! [before]
  (let [registry (stest-instrumented-vars-atom)
        additions (set/difference (set (keys @registry))
                                  (set (keys (:entries before))))]
    (when (seq additions)
      (stest/unstrument (map stest/->sym additions)))
    (doseq [[v root] (:roots before)]
      (when-not (identical? root @v)
        (alter-var-root v (constantly root))))
    (reset! registry (:entries before))
    (let [after (instrumentation-state)]
      (when-not (same-instrumentation-state? before after)
        (throw (ex-info "Failed to restore spec instrumentation state"
                        {:before before :after after}))))))

(defn- with-fdefs-loaded [f]
  (let [registry (stest-instrumented-vars-atom)]
    (locking registry
      (let [before (instrumentation-state)]
        (try
          ;; This namespace registers every public fdef and then auto-instruments
          ;; them. Suppress only that eager instrumentation while loading; any
          ;; additions made inside `f` are still removed in `finally`.
          (with-redefs [stest/instrument (fn [& _] [])]
            (require 'github.copilot-sdk.instrument))
          (f)
          (finally
            (restore-instrumentation! before)))))))

(defn- namespace-entry [namespace]
  (let [vars (public-vars namespace)]
    (cond-> {:vars vars
             :fdefs (fdef-entries namespace vars)}
      (= idiom-spec-ns namespace) (assoc :spec-keys (spec-keys)))))

(defn- compute-surface []
  {:format-version format-version
   :namespaces
   (into (sorted-map)
         (map (fn [namespace]
                [namespace (namespace-entry namespace)]))
         public-namespaces)})

(defn current-surface
  "The live supported public surface as a deterministic data snapshot."
  []
  (with-fdefs-loaded
    #(assert-stable-edn! :surface (compute-surface))))

(defn- validate-snapshot! [snapshot]
  (when-not (= format-version (:format-version snapshot))
    (throw
     (ex-info
      (str "Unsupported API-surface snapshot format "
           (pr-str (:format-version snapshot))
           ". Regenerate it with `bb api-surface:update`.")
      {:expected-format-version format-version
       :actual-format-version (:format-version snapshot)})))
  (when-not (map? (:namespaces snapshot))
    (throw
     (ex-info
      "Invalid API-surface snapshot: `:namespaces` must be a map. Regenerate it with `bb api-surface:update`."
      {:snapshot snapshot})))
  (doseq [[namespace {:keys [vars fdefs spec-keys] :as entry}]
          (:namespaces snapshot)]
    (when-not (and (map? entry)
                   (map? vars)
                   (map? fdefs)
                   (or (not (contains? entry :spec-keys))
                       (vector? spec-keys)))
      (throw
       (ex-info
        "Invalid API-surface namespace entry. Regenerate it with `bb api-surface:update`."
        {:namespace namespace :entry entry}))))
  snapshot)

(defn read-snapshot
  "Read and validate the checked-in snapshot, or nil if it is missing."
  []
  (when-let [resource (io/resource snapshot-resource)]
    (with-open [reader (io/reader resource)]
      (validate-snapshot!
       (edn/read (java.io.PushbackReader. reader))))))

(defn- vector-lines [values]
  (str "["
       (str/join "\n    " (map pr-str values))
       "]"))

(defn- map-lines [entries]
  (str "{"
       (str/join "\n    "
                 (map (fn [[key value]]
                        (str (pr-str key) " " (pr-str value)))
                      entries))
       "}"))

(defn- namespace-lines
  [[namespace {:keys [vars fdefs spec-keys] :as entry}]]
  (str (pr-str namespace) "\n"
       "  {:vars\n"
       "   " (map-lines vars) "\n"
       "   :fdefs\n"
       "   " (map-lines fdefs)
       (when (contains? entry :spec-keys)
         (str "\n"
              "   :spec-keys\n"
              "   " (vector-lines spec-keys)))
       "}"))

(defn- edn-string [surface]
  (let [snapshot
        (str ";; AUTO-GENERATED public API-surface snapshot. Do not edit by hand.\n"
             ";; Regenerate with `bb api-surface:update` after an intentional\n"
             ";; public-contract change. See github.copilot-sdk.api-surface.\n"
             "{:format-version " (:format-version surface) "\n"
             " :namespaces\n"
             " {\n  "
             (str/join "\n  " (map namespace-lines (:namespaces surface)))
             "\n }}\n")]
    (when (re-find #"__\d+(?:__auto__|#)|#object\[|(?:^|[.$])proxy\$"
                   snapshot)
      (throw (ex-info "Unstable generated content reached API snapshot output"
                      {:snapshot snapshot})))
    snapshot))

(defn write-snapshot! []
  (let [surface (current-surface)
        file (snapshot-source-file)
        namespace-count (count (:namespaces surface))
        var-count (transduce (map (comp count :vars val))
                             +
                             (:namespaces surface))
        fdef-count (transduce (map (comp count :fdefs val))
                              +
                              (:namespaces surface))
        spec-count (transduce (map (comp count :spec-keys val))
                              +
                              (:namespaces surface))]
    (io/make-parents file)
    (spit file (edn-string surface))
    (println "Wrote" (str file)
             (str "(" namespace-count " namespaces, "
                  var-count " vars, "
                  fdef-count " fdefs, "
                  spec-count " spec keys)"))))

(defn -main [& _]
  (write-snapshot!))
